context:
  name: raysect
  version: "0.8.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/${{ name|lower }}/source/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 6b47f06cf58e6bf021606aa3a7b42f0a200f63d8695e01a6274941dedf3685bb

build:
  script: ${{ PYTHON }} -m pip install --no-build-isolation --no-deps -vv .
  number: 0
  skip:
    - win

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - setuptools
        - cython <3.0
        - numpy
  host:
    - python
    - pip
    - setuptools
    - cython <3.0
    - numpy
  run:
    - python
    - matplotlib-base

tests:
  - python:
      imports:
        - raysect
        - raysect.core
        - raysect.optical
        - raysect.primitive

  - script:
    - if: unix
      then:
        - python -c "import raysect; print(raysect.__path__[0])" | xargs python -m unittest discover -v -s
    - if: win
      then:
        - python -c "import raysect; print(raysect.__path__[0])" | python -m unittest discover -v -s ?



about:
  homepage: http://www.raysect.org
  summary: A Ray-tracing Framework for Science and Engineering
  license: BSD-3-Clause
  license_file: LICENSE.txt
  documentation: http://www.raysect.org
  repository: https://github.com/raysect/source.git

extra:
  recipe-maintainers:
    - munechika-koyo
