context:
  name: raysect
  version: "0.9.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/${{ name|lower }}/source/archive/refs/tags/v${{ version }}.tar.gz
  sha256: cdce889c649b0432dc670363cb9ebd0a3ca9c4a8916990f59acf1246f0077668
  patches:
    - cross_compile.patch

build:
  number: 0
  skip:
    - win

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - ninja
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - pkg-config
        - cython >=3.1
        - numpy
  host:
    - python
    - python-build
    - pkg-config
    - pip
    - meson-python
    - setuptools
    - setuptools-scm
    - cython >=3.1
    - numpy
  run:
    - python
    - matplotlib-base
    - opencv
  run_exports:
    - ${{ pin_subpackage("raysect", lower_bound="x.x.x", upper_bound="x.x.x") }}

tests:
  - python:
      imports:
        - raysect
        - raysect.core
        - raysect.optical
        - raysect.primitive

  - script:
      - if: unix
        then:
          - python -c "import raysect; print(raysect.__path__[0])" | xargs python -m unittest discover -v -s
      - if: win
        then:
          - python -c "import raysect; print(raysect.__path__[0])" | python -m unittest discover -v -s ?



about:
  homepage: http://www.raysect.org
  summary: A Ray-tracing Framework for Science and Engineering
  license: BSD-3-Clause
  license_file: LICENSE.txt
  documentation: http://www.raysect.org
  repository: https://github.com/raysect/source.git

extra:
  recipe-maintainers:
    - munechika-koyo
